name: lmgonzalves
description: I am a front-end developer.
url: http://lmgonzalves.github.io
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
paginate: 9
paginate_path: "/page/:num/"
excerpt_separator: <!--more-->
twitter_username: lmgonzalves
permalink: /:year/:month/:day/:title/