name: lmgonzalves
description: I am a front-end developer (HTML5, CSS3, SASS, Bootstrap, JavaScript, jQuery, AngularJS). And I also like to develop back-end APIs (NodeJS and Django).
url: http://lmgonzalves.github.io
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
paginate: 9
paginate_path: "/page/:num/"
excerpt_separator: <!--more-->
twitter_username: lmgonzalves
permalink: /:year/:month/:day/:title/